### ISSUE TITLE
Missing PHP 8.0 dependencies

### ISSUE THREAD

**Issue by Mazamazine** [AlternC/alternc-php-fpm#20]
Commit #27c3b5e introduces PHP 8.0 support, but the dependencies are missing in debian/control.
I'll push a PR for that.

**Comment by camlafit** [comment]
Hello

Next release will be php version agnostic :) Will better to accept also 8.1 and 8.2 without any packaging change.

But as recommended dependency why not.

**Comment by camlafit** [comment]
Hello

Yes indeed we can close #22 
You can do a look on this branch [issue-8](https://github.com/AlternC/alternc-php-fpm/tree/issue-8) (wrong naming should issue-22 (#8 has opened the initial work about php8.x support) 

Actually miss a correct clean detection; when an old php packaging is deleted. I've only forgot to push my correction about this.
To note package is actually tested on some servers (mainly 3.5) ; and should be 3.3 and 3.5 agnostic.

**Comment by camlafit** [comment]
managed by #18
