### ISSUE TITLE
erreur dans la requête d'insertion des version de php-fpm (si alternc-ssl est installé?)

### ISSUE THREAD

**Issue by quenenni** [AlternC/alternc-php-fpm#4]
https://github.com/AlternC/alternc-php-fpm/blob/ea3951cc643f3ae23f1d72f4cafb89fcacd845eb/debian/postinst#L10

Les requêtes d'insertion ont un champ trop peu:
```
#1136 - Column count doesn't match value count at row 1
```
Alternc-certbot qui ajoute cette colonne?
J'ai rajouté un 1 en dernière colonne pour avoir l'accès http et/ou https pour les vhost php-fpm
```
INSERT IGNORE INTO domaines_type VALUES ('php70-fpm','PHP 7.0 FPM','DIRECTORY','%SUB% IN A @@PUBLIC_IP@@','txt,defmx,defmx2,mx,mx2','ALL',0,0,0,0,0,1)
```

**Comment by quenenni** [comment]
doublon de https://github.com/AlternC/alternc-php-fpm/issues/2

**Comment by quenenni** [comment]
Mais où est ajouté cette colonne?

La colonne de différence avec un autre serveur (qui n'a pas alternc-certbot) est la colonne 'has_https_option'

Ca me semble une claire référence à ce que ce soit alternc-certbot qui l'a ajouté.
(si je met 1 comme valeur, le champ des choix du certificat apparaissent, et avec 0, non)

Mais je viens de fouiller le code de alternc-certbot et aucune référence à cette colonne ou modification de la table domaines_type.

**Comment by quenenni** [comment]
Trouvé.
Cette colonne est créée par le paquet AlternC et non AlternC-certbot depuis la version 3.5.0.1 et notre autre serveur est à la version 3.4.6.
https://github.com/AlternC/AlternC/blob/master/install/upgrades/3.5.0.1.sql

**Comment by camlafit** [comment]
Hello

Solved with d75489c4b4fae0307b88814b262060bca57189a1 and 8a56055aa3bce7292d2dd784a616843fb46ad4dc
